version: '3'

services:
  rails:
    image: chatwoot/chatwoot:latest
    depends_on:
      - postgres
      - redis
      - mailhog
      - sidekiq
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/chatwoot
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY_BASE=1234567890abcd

    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    image: chatwoot/chatwoot:latest
    depends_on:
      - postgres
      - redis
      - mailhog
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/chatwoot
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY_BASE=1234567890abcd
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data/redis

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres:
  redis:
