# This is used by Netlify via netlify.toml to set environment variables for specific environments
# https://docs.netlify.com/configure-builds/file-based-configuration/#inject-environment-variable-values

[context.deploy-preview.environment]
  GATSBY_COMMUNITY_URL="https://community-test.debtcollective.org"
  GATSBY_DONATE_API_URL = "https://membership-test.debtcollective.org/donate"
  GATSBY_FUNDS_API_URL = "https://membership-test.debtcollective.org/funds"
  GATSBY_HOST_URL = "https://development.debtcollective.org"
  GATSBY_MEMBERSHIP_API_URL = "https://membership-test.debtcollective.org/subscriptions"
  GATSBY_MEMBERSHIP_URL = "https://membership-test.debtcollective.org"

[context.development.environment]
  GATSBY_COMMUNITY_URL="https://community-test.debtcollective.org"
  GATSBY_DONATE_API_URL = "https://membership-test.debtcollective.org/donate"
  GATSBY_FUNDS_API_URL = "https://membership-test.debtcollective.org/funds"
  GATSBY_HOST_URL = "https://development.debtcollective.org"
  GATSBY_MEMBERSHIP_API_URL = "https://membership-test.debtcollective.org/subscriptions"
  GATSBY_MEMBERSHIP_URL = "https://membership-test.debtcollective.org"

[build]
  functions = 'functions'
[[redirects]]
  from = "/api/*"
  to="/.netlify/functions/:splat"
  status=200
[[redirects]]
  from = "/flick-of-the-pen"
  to="/flick-of-a-pen"
  status=301
[[redirects]]
  from = "/flickofapen"
  to="/flick-of-a-pen"
  status=301
[[redirects]]
  from = "/hub"
  to="https://membership.debtcollective.org/membership"
  status=301
